[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hvdocs"
authors = [{name = "Rissoter", email = "rissoter@gmail.com"}]
dynamic = ["version", "description"]
